twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        api_key: '%env(API_KEY)%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
