twig:
    file_name_pattern: '*.twig'
    globals:
        api_key: '%env(API_KEY)%'
        highlander: '@App\Service\Highlander'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
