controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


weather_highlander_says:
    path: /weather/highlander-says/{threshold<\d+>?50}
    controller: App\Controller\WeatherController::highlanderSays

weather_highlander_says_guess:
    path: /weather/highlander-says/{guess}
    controller: App\Controller\WeatherController::highlanderSaysGuess
